### ISSUE TITLE
返回对象里加入获取运限的方法｜Add a function to get horoscope in the response object

### ISSUE THREAD

**Issue by SylarLong** [SylarLong/astro#1]
### 摘要（Summary）

🇨🇳
现在返回的星盘对象和获取流耀的方法是分开的，这样在调用的时候不是很方便，所以需要在返回的对象里面加入一个方法来获取制定日期的运限信息以及流曜。

🇺🇸
The astrolabe object and get horoscope stars function are detached. It's not convenient. So it would be better to add a function to get horoscope of specific date.

---

#### 需求（Requirements）

🇨🇳
- 传入时间可选，当没传入时间的时候默认获取当前日期
- 返回数据应该包含当前时间大限、流年、流月以及流日的索引
- 返回虚岁以便通过虚岁定位小限宫位
- 返回大限以及流年的流曜
- 返回大限、流年、流月以及流日的四化

🇺🇸

- Date can be optional. When no date is provided, it will default to the current date.
- The returned data should include the indexes of the decadal scope, yearly scope, monthly scope, and daily scope.
- Return nominal age to determine the age-related scope.
- Return decadal and yearly scope stars.
- Return mutagen of decadal yearly monthly and daily scope.

**Comment by SylarLong** [comment]
### 运限信息定义 （Horoscope definition）

```ts
export type HoroscopeItem = {
  index: number;
  heavenlyStem: HeavenlyStem;
  palaceNames: PalaceName[];
  mutagen: (typeof heavenlyStems)[HeavenlyStem]['mutagen'];
  stars?: Star[][];
};

export type Horoscope = {
  lunarDate: string;
  solarDate: string;
  decadal: HoroscopeItem;
  age: { index: number; nominalAge: number };
  yearly: HoroscopeItem;
  monthly: HoroscopeItem;
  daily: HoroscopeItem;
};
``

`Astrolabe`  对象新增方法 `horoscope` 方法。调用方法如下：

```ts

import { astro } from '@sylarlong/astro';

// 通过阳历获取星盘信息
// generate astrolabe by solar date
const astrolabe = astro.astrolabeBySolarDate('2000-8-16', 2, '女');

// 获取运限信息
astrolabe.horoscope('2023-8-16');

```

**Comment by 556isback** [comment]
可以把流时加上吗?

**Comment by SylarLong** [comment]
> 可以把流时加上吗?

可以的哦，后续小版本会加上的。感谢关注～ 👍

**Comment by SylarLong** [comment]
你好，@556isback ~👋

我收到你说运限天干地支有问题的邮件，但是没有发现comment，请问是哪个地方的干支出现了问题呢？非常感谢你的指正。也非常欢迎你创建Issue来帮助我改进程序。

希望能得到你的回复，以便让我知道是哪里出现错误而及时纠正错误。

**Comment by SylarLong** [comment]
@556isback 好的，如果遇到问题或者有任何建议，欢迎到 [discussion](https://github.com/SylarLong/astro/discussions) 里讨论。
