### ISSUE TITLE
加入流时信息｜Add timely scope information

### ISSUE THREAD

**Issue by SylarLong** [SylarLong/astro#3]
### 摘要（Summary）

🇨🇳
在运限信息中加入流时信息。

🇺🇸
Add timely scope information to horoscope.

---

Ref. https://github.com/SylarLong/astro/issues/1#issuecomment-1685296862

#### 需求（Requirements）

🇨🇳
- 包含流时所在宫位索引
- 流时天干
- 流时四化

🇺🇸
- timely scope index should be included
- heavenly stem of timely scope should be included
- mutagen of timely scope should be included.

> 是否加入流时星耀，还需在今后大家的使用中来决定。

**Comment by 556isback** [comment]
天干地支是不是错了?
